language: ruby
sudo: false
cache: bundler
before_install: gem install bundler
script: 'bundle exec rake'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - rbx
  - jruby-19mode
  - jruby-head
bundler_args: '--path vendor/bundle'

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
