language: ruby
before_install: gem install bundler
script: 'ci/run.rb'
rvm:
  - 1.8.7
  - 1.9.3
  - rbx-19mode
  - rbx-18mode
  - 2.0.0
bundler_args: '--path vendor/bundle'
env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=4.0"

matrix:
  allow_failures:
    - env: "RAILS_VERSION=4.0"
    - rvm: 2.0.0
  exclude:
    - rvm: 1.8.7
      env: "RAILS_VERSION=4.0"
    - rvm: rbx-18mode
      env: "RAILS_VERSION=4.0"
