language: ruby
before_install: gem install bundler
script: 'ci/run.rb'
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
  - jruby-19mode
  - jruby-head
bundler_args: '--path vendor/bundle'
env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=4.0"

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
