source "http://rubygems.org"
gemspec

gem 'redis-store', '~> 1.1.0', :path => File.expand_path('../../redis-store', __FILE__)
gem 'i18n'
gem 'SystemTimer', :platform => :mri_18

version = ENV["RAILS_VERSION"] || "3.2"

rails = case version
when "master"
  {:github => "rails/rails"}
else
  "~> #{version}.0"
end

gem "rails", rails
