source "http://rubygems.org"
gemspec

gem 'redis-store',      '1.1.0.rc', :path => File.expand_path('../../redis-store',      __FILE__)
gem 'redis-rack-cache', '1.1.rc2',  :path => File.expand_path('../../redis-rack-cache', __FILE__)
gem 'redis-rack',       '1.3.5.rc', :path => File.expand_path('../../redis-rack', __FILE__)
gem 'SystemTimer', :platform => :mri_18
