source "http://rubygems.org"
gemspec

gem 'redis-store',         '~> 1.1.0', :path => File.expand_path('../../redis-store',         __FILE__)
gem 'redis-activesupport', '~> 3.1.0', :path => File.expand_path('../../redis-activesupport', __FILE__)
gem 'redis-actionpack',    '~> 3.1.0', :path => File.expand_path('../../redis-actionpack',    __FILE__)